name: TrollCommandsPlusPlus
main: me.egg82.tcpp.TrollCommandsPlusPlus
version: 1.0.1
commands:
  troll:
    description: Same as /help TrollCommandsPlusPlus [page]
    usage: /troll [page]
  vaporize:
    description: Explodes target with a specified power. To disable block damage, use a negative value.
    usage: /vaporize <player> [power]
    aliases: [vap]
  lift:
    description: It's like flying, but only in one direction. And probably without a soft landing.
    usage: /lift <player>
  creep:
    description: Spawns a charged creeper at the target's location.
    usage: /creep <player>
  swap:
    description: Swaps two players' locations.
    usage: /swap <player> <player>
  entomb:
    description: A premature burial.
    usage: /entomb <player>
  slowpoke:
    description: Applies a slowness effect to the player.
    usage: /slowpoke <player>
  electrify:
    description: Thine enemy shalt feel the wrath of many angry gods.
    usage: /electrify <player>
    aliases: [elec]
  zombify:
    description: I hope they came prepared for the zombie apocalypse.
    usage: /zombify <player>
    aliases: [zomb]
  slap:
    description: Slaps the player. Yep. Slaps them.
    usage: /slap <player> [force]
  cannon:
    description: Shoots a primed TNT wherever you're looking.
    usage: /cannon [speed]
  banish:
    description: Teleports the player to a random location.
    usage: /banish <player> [range]
  bomb:
    description: May balls of fire rain down upon thine enemy.
    usage: /bomb <player>
  freeze:
    description: Don't like someone? Turn them into a statue!
    usage: /freeze <player>
  comet:
    description: Shoots a fireball of adjustable power.
    usage: /comet [power]
  stampede:
    description: Unleashes a herd of mad cows on the player.
    usage: /stampede <player>
  haunt:
    description: Toggles random sounds near the target.
    usage: /haunt <player>
  lure:
    description: Attracts nearby monsters to the target player.
    usage: /lure <player>
  garble:
    description: ..And now the player makes even less sense!
    usage: /garble <player>
  weakling:
    description: Applies a weakness effect to the player.
    usage: /weakling <player>
  spin:
    description: This might make them a bit dizzy.
    usage: /spin <player>