name: TrollCommandsPlusPlus
main: me.egg82.tcpp.TrollCommandsPlusPlus
version: 4.18.37
softdepend: [LibsDisguises,iDisguise,ProtocolLib]
commands:
  troll:
    description: TrollCommands++
    usage: |
      -= Available Commands =-
      /troll alone <player>: Hides all other players from the specified player.
      /troll amnesia <player>: Screws with the player's chat in weird ways.
      /troll annoy <player>: Hrmm. Hmm.. Hrrm.. Hrm. Hm. Hmm..
      /troll anvil <player>: Now who could have put that up there?
      /troll attachcommand <topic>: The specified command (topic) will be attached to an item. The next time this item is picked up, it will run the command as the payer that picked the item up..
      /troll banish <player> [range]: Teleports the player to a random location.
      /troll bludger <player>: Nasty little buggers.
      /troll bomb <player>: May balls of fire rain down upon thine enemy.
      /troll brittle <player>: They're made of glass!
      /troll burn <player>: AHH! FIRE! FIRE! FIIREE!!
      /troll cannon [speed] [power]: Shoots a primed TNT wherever you're looking of adjustable speed and power.
      /troll clumsy <player>: Careful, or you'll end up dropping all of your stuff!
      /troll comet [speed] [power]: Shoots a fireball of adjustable speed and power.
      /troll control <player>: Allows you to take control of a player. Oooh, spoooky!
      /troll convert <player> [type]: I hope they REALLY like potatoes. Or whatever you want, really.
      /troll creep <player>: Spawns a charged creeper at the player's location.
      /troll display <player>: Put your friends and enemies on display!
      /troll effect <player> <effect>: Applies the specified effect to the player indefinitely, or removes it if it has already been applied.
      /troll electrify <player>: Thine enemy shalt feel the wrath of many angry gods.
      /troll empower: Empowers (or disempowers) the next player or mob you right-click. Give them the strength to defeat thine enemy!
      /troll enchant <type> [level]: Enchants (or disenchants) the item you're holding with the specified enchantment. Optionally takes a level for the enchantment.
      /troll entomb <player>: A premature burial.
      /troll explodebreak <player>: The next block the player mines explodes!
      /troll explodebuild <player>: The next block the player places explodes!
      /troll fakecrash <player>: Kicks the player with a nice little (or not-so-little) java exception message.
      /troll fakeop <player>: Sends a message to the player saying they are opped. They will not be.
      /troll fill <player> <type>: Fills the player's inventory with the specified type. Because of course it does!
      /troll flip <player>: Makes the player do a 180.
      /troll foolsgold <player>: Ore! Ore everywhere, and not a drop to drink.
      /troll freeze <player>: Don't like someone? Turn them into a statue!
      /troll garble <player>: ..And now the player makes even less sense!
      /troll grantwishes <player>: Be careful what you say!
      /troll haunt <player>: Toggles random sounds near the player.
      /troll help <topic>: Shows the usage and description for the specified command.
      /troll hottub <player>: Drops the player is a nice, hot bath.
      /troll hurt <player>: Where is all this damage coming from?!
      /troll infinity <player>: Makes the player fall indefinitely.
      /troll inspect <player>: Allows you to "inspect" the player's inventory.
      /troll invert <player>: Left is right, up is down! Only works for flight.
      /troll kill <player> [seconds]: Kills a player with a delay.
      /troll lag <player>: Makes the player experience fake lag. Does not affect the server.
      /troll lavabreak <player>: The next block a player breaks turns to lava.
      /troll lavabuild <player>: The next block a player places turns to lava.
      /troll levitate <player>: Ascends the player to the heavens forever. Drops them like a rock when removed.
      /troll lift <player>: It's like flying, but only in one direction. And probably without a soft landing.
      /troll lock <player>: Prevents the player from interacting with their inventory or hotbar. They didn't REALLY need their sword, did they?
      /troll lure <player>: Attracts nearby monsters to the player.
      /troll nightmare <player>: Summons a waking nightmare for the player.
      /troll nopickup <player>: Stops the player from picking up items.
      /troll popup <player>: Randomly opens and closes the player's inventory.
      /troll portal <player>: The quickest way to The End!
      /troll public <player>: Gives everyone the chance to "inspect" the player's inventory. Freedom of information!
      /troll radiate <player>: Makes the player radiate toxicity, slowly killing all plant and animal-life around them.
      /troll randombreak <player>: Oh, diamonds-! Wait, why did I get dirt?
      /troll randombuild <player>: Build your house out of.. Everything!
      /troll randomdrop <player>: Drop ALL of the things!
      /troll randompotion <player>: Wait, what did I drink again?
      /troll randomspeed <player>: My legs just take me wherever they want!
      /troll rewind <player>: Makes the player's time run backwards at speed. Does not affect the server.
      /troll search <player> [search]: Opens a GUI with available commands for trolling the specified player. Optionally takes a search argument.
      /troll slap <player>: Slaps the player. Yep. Slaps them.
      /troll slender <player>: Blinds and slows the player, then sends an enderman after them.
      /troll slowundo <player>: Slowly undoes any block changes the player makes.
      /troll snowballfight <player>: The player will fire snowballs instead of arrows. Good hunting, Will!
      /troll spam <player>: Spams the player's chat with useless junk.
      /troll sparta <player>: Our arrows will blot out the sun! .. Pincushion-y!
      /troll spin <player> [speed]: This might make them a bit dizzy. Optionally allows you to adjust how fast they spin!
      /troll spoil <player>: Ensures they quickly run out of food.
      /troll squid <player>: .. Why is it raining squids?
      /troll stampede <player>: Unleashes a herd of mad cows on the player.
      /troll starve <player>: They must have a REALLY fast metabolism!
      /troll stop <player>: Stops any currently-active trolls against the player.
      /troll surround <player> <mob>: Surrounds the player with a specific mob type.
      /troll swap <player> <player>: Swaps two players' locations, Freaky Friday style.
      /troll time <player> <time>: Sets the player's time to the time specified permanently. Does not affect the server.
      /troll trickle <player>: They're leaking XP all over the place!=
      /troll useless <player>: Renames all of the player's items to Useless.
      /troll vaporize <player>: Explodes the player with a specified power. To disable block damage, use a negative value.
      /troll vegetable <player> [type]: Turns the player into a vegetable. Potato by default, but you may optionally provide the vegetable type. Potato simulator 20XX!
      /troll void <player>: Think Journey to the Center of the Earth, except with death at the end.
      /troll vomit <player>: They just can't keep anything down, can they?
      /troll whoami <player>: Seriously, though. Who even am I? (Changes the player's name constantly)
    aliases: [t]