# Redis provides the ability to push instant commands across the network
# Even if you use messaging, this can be used as a backup source
# Redis is entirely optional, though disabling it AND messaging WILL disable /gtroll
redis:
  enabled: false
  address: ''
  port: 6379
  pass: ''

# Messaging is used to push instant commands across the network
# Even if you use Redis, this can be used as a backup source
# Messaging is entirely optional, though disabling it AND Redis WILL disable /gtroll
messaging:
  enabled: false
  # The type of messaging to use
  # Values can be 'bungee' ('default') or 'rabbit'
  # If 'default' or 'bungee' is selected, please be sure to use TC++ for BungeeCord!
  type: 'bungee'
  # Values to fill in if using Rabbit messaging
  rabbit:
    address: ''
    port: 5672
    user: 'guest'
    pass: 'guest'

# Config version, no touchy plz
version: 2.0