name: TrollCommandsPlusPlus
main: me.egg82.tcpp.TrollCommandsPlusPlus
version: 6.28.53
author: egg82
description: For the people that really hate their friends
softdepend: [LibsDisguises,iDisguise,ProtocolLib,PowerNBT]
commands:
  gtroll:
    description: Same as /troll, except it can be used cross-server (if configured)
    usage: /gtroll <troll> [options]
  troll:
    description: TrollCommands++
    usage: |
      -= Available Commands =-
      /troll alone <player>: (Toggleable) Hides all other players from the specified player.
      /troll amnesia <player>: (Toggleable) Screws with the player's chat in weird ways.
      /troll annoy <player>: (Toggleable) Hrmm. Hmm.. Hrrm.. Hrm. Hm. Hmm..
      /troll anvil <player>: Now who could have put that up there?
      /troll attach <topic>: (Undoable) The specified command (topic) will be attached to an item. The next time this item is picked up, it will run the command as the payer that picked the item up..
      /troll banish <player> [range]: Teleports the player to a random location.
      /troll bludger <player>: (Toggleable) Nasty little buggers. (Removed on quit, explode)
      /troll bomb <player>: (Toggleable) May balls of fire rain down upon thine enemy. (Removed on death)
      /troll brittle <player>: (Toggleable) They're made of glass! (Removed on death)
      /troll burn <player>: (Toggleable) AHH! FIRE! FIRE! FIIREE!! (Removed on death)
      /troll cannon [speed] [power]: Shoots a primed TNT wherever you're looking of adjustable speed and power.
      /troll chat <player> <message>: Chat or run a command as a player using their own permissions.
      /troll duck <player>: (Toggleable) Turns the player into a duckchicken. (Removed on quit)
      /troll clumsy <player>: (Toggleable) Careful, or you'll end up dropping all of your stuff!
      /troll comet [speed] [power]: Shoots a fireball of adjustable speed and power.
      /troll control <player>: (Toggleable) Allows you to take control of a player. Oooh, spoooky! (Removed on quit)
      /troll convert <player> <type>: (Undoable) I hope they REALLY like potatoes. Or whatever you want, really.
      /troll creep <player>: Spawns a few charged creepers at the player's location.
      /troll deathtag <player>: (Toggleable) The next player the selected player says dies, and then the death tag transfers to them.
      /troll display <player>: (Toggleable) Put your friends and enemies on display! (Removed on quit)
      /troll effect <player> [effect]: (Undoable) Applies the specified effect to the player indefinitely, or removes it if it has already been applied. Optionally removes all applied effects.
      /troll electrify <player>: (Toggleable) Thine enemy shalt feel the wrath of many angry gods. (Removed on death)
      /troll empower: (Undoable) Empowers (or disempowers) the next player or mob you right-click. Give them the strength to defeat thine enemy! (Removed on quit)
      /troll enchant <type> [level]: (Undoable) Enchants (or disenchants) the item you're holding with the specified enchantment. Optionally takes a level for the enchantment.
      /troll entomb <player>: A premature burial.
      /troll explodebreak <player>: (Toggleable) The next block the player mines explodes!
      /troll explodebuild <player>: (Toggleable) The next block the player places explodes!
      /troll fakecrash <player>: Kicks the player with a nice little (or not-so-little) java exception message.
      /troll fakeop <player>: Sends a message to the player saying they are opped. They will not be.
      /troll fill <player> <type>: (Undoable) Fills the player's inventory with the specified type. Because of course it does!
      /troll flip <player>: Makes the player do a 180.
      /troll foolsgold <player>: (Toggleable) Ore! Ore everywhere, and not a drop to drink.
      /troll freeze <player>: (Toggleable) Don't like someone? Turn them into a statue!
      /troll garble <player>: (Toggleable) ..And now the player makes even less sense!
      /troll grantwishes <player>: (Toggleable) Be careful what you say!
      /troll haunt <player>: (Toggleable) Toggles random sounds near the player.
      /troll help <topic>: Shows the usage and description for the specified command.
      /troll hottub <player>: Drops the player is a nice, hot bath.
      /troll hurt <player>: (Toggleable) Where is all this damage coming from?! (Removed on death)
      /troll hydra: (Undoable) Enables (or disables) the power of hydra on the next mob you right-click. Hail Hydra!
      /troll infinity <player>: (Toggleable) Makes the player fall indefinitely.
      /troll inspect <player>: Allows you to "inspect" the player's inventory.
      /troll invert <player>: (Toggleable) Left is right, up is down! Reverses the player's flight controls. (Removed on quit)
      /troll kill <player> [seconds]: (Toggleable) Kills a player with a delay. (Removed on death)
      /troll lag <player>: (Toggleable) Makes the player experience fake lag. Does not affect the server.
      /troll lavabreak <player>: (Toggleable) The next block a player breaks turns to lava.
      /troll lavabuild <player>: (Toggleable) The next block a player places turns to lava.
      /troll levitate <player>: (Toggleable) Ascends the player to the heavens forever. Drops them like a rock when removed.
      /troll lift <player>: (Toggleable) It's like flying, but only in one direction. And probably without a soft landing.
      /troll lock <player>: (Toggleable) Prevents the player from interacting with their inventory or hotbar. They didn't REALLY need their sword, did they?
      /troll lsd <player>: (Toggleable) RAAAAIIINNNNBOOOOWWWW! Does not affect the server.
      /troll luckyblock [luck]: (Undoable) Turns the block in your hand into a lucky/unlucky block. You may optionally provide a "luck chance" defining how high the "luck" value vs "unluck" is.
      /troll lure <player>: (Toggleable) Continuously attracts nearby monsters to the player.
      /troll midastouch <player> [type]: (Toggleable) Any blocks the player touches turns to GOLD (or whatever you specify).
      /troll moist <player>: (Toggleable) Would you moist my moistness, please? (Requires internet connection)
      /troll necro <player>: (Toggleable) Let's play "pretend you're a skeleton"! (Removed on quit)
      /troll nightmare <player>: (Toggleable) Summons a waking nightmare for the player.
      /troll nopickup <player>: (Toggleable) Stops the player from picking up items.
      /troll popup <player>: (Toggleable) Randomly opens and closes the player's inventory.
      /troll portal <player>: The quickest way to The End!
      /troll public <player>: Gives everyone the chance to "inspect" the player's inventory. Freedom of information!
      /troll radiate <player>: (Toggleable) Makes the player radiate toxicity, slowly killing all plant and animal-life around them.
      /troll random <player>: (Toggleable) Lazy? Do something random!
      /troll randombreak <player>: (Toggleable) Oh, diamonds-! Wait, why did I get dirt?
      /troll randombuild <player>: (Toggleable) Build your house out of.. Everything!
      /troll randomdrop <player>: (Toggleable) Drop ALL of the things!
      /troll randommenu <player>: (Toggleable) Why is my chest now an anvil?
      /troll randompotion <player>: (Toggleable) Wait, what did I drink again?
      /troll randomspeed <player>: (Toggleable) My legs just take me wherever they want! (Removed on quit)
      /troll rewind <player>: (Toggleable) Makes the player's time run backwards at speed. Does not affect the server.
      /troll run <player> <topic>: Run a command (topic) as a player using your permissions.
      /troll search <player> [search]: Opens a GUI with available commands for trolling the specified player. Optionally takes a search argument.
      /troll slap <player>: Slaps the player. Yep. Slaps them.
      /troll slender <player>: Blinds and slows the player, then sends an enderman after them.
      /troll slowundo <player>: (Toggleable) Slowly undoes any block changes the player makes.
      /troll snowballfight <player>: (Toggleable) The player will fire snowballs instead of arrows. Good hunting, Will!
      /troll spam <player>: (Toggleable) Spams the player's chat with useless junk.
      /troll sparta <player>: (Toggleable) Our arrows will blot out the sun! .. Pincushion-y! (Removed on death)
      /troll spawnbreak <player> <type>: (Toggleable) Whenever the player breaks a block it will spawn a mob that targets the player.
      /troll spin <player> [speed]: (Toggleable) This might make them a bit dizzy. Optionally allows you to adjust how fast they spin!
      /troll spoil <player>: (Toggleable) Ensures they quickly run out of food.
      /troll squid <player>: (Toggleable) .. Why is it raining squids?
      /troll stampede <player>: Unleashes a herd of mad cows on the player.
      /troll starve <player>: (Toggleable) They must have a REALLY fast metabolism! (Removed on death)
      /troll stop <player>: Stops and undoes any currently-active trolls against the player.
      /troll surround <player> <mob>: Surrounds the player with a specific mob type.
      /troll swap <player> <player>: Swaps two players' locations, Freaky Friday style.
      /troll time <player> <time>: (Undoable) Sets the player's time to the time specified permanently. Does not affect the server.
      /troll trickle <player>: (Toggleable) They're leaking XP all over the place!
      /troll trip <player> [clone]: Trips the player, making them drop their entire inventory. Optional true/false argument for cloning the inventory instead of removing it. Default is false.
      /troll useless <player>: Renames all of the player's items to Useless.
      /troll vaporize <player>: Explodes the player with a specified power. To disable block damage, use a negative value.
      /troll vegetable <player> [type]: (Toggleable) Turns the player into a vegetable. Potato by default, but you may optionally provide the vegetable type. Potato simulator 20XX! (Removed on quit)
      /troll void <player>: Think Journey to the Center of the Earth, except with death at the end.
      /troll vomit <player>: (Toggleable) They just can't keep anything down, can they?
      /troll whoami <player>: (Toggleable) Seriously, though. Who even am I? (Changes the player's name constantly)